### ISSUE TITLE
Hero Banners do not align correctly

### ISSUE THREAD

**Issue by whoozwah** [davidkgriggs/PlayniteModernUI#11]
I use steam hero banners (1920x620) and they do not show up correctly. Is it possible to "fit to width" and then top align them with a bottom fade to a neutral color like gray or black on the game details screen?

**Comment by davidkgriggs** [comment]
Can you send a screenshot of what they currently look like?

**Comment by davidkgriggs** [comment]
Fixed in v1.0.6
