### ISSUE TITLE
How long to beat times are not aligned on bigger font size 

### ISSUE THREAD

**Issue by C0D10X** [davidkgriggs/PlayniteModernUI#13]
![Screenshot_20211015-103315__01.jpg](https://user-images.githubusercontent.com/92644280/137596359-1c06aca1-d73f-4a4b-8b4f-cf8f1f12664f.jpg)

**Comment by C0D10X** [comment]
Problem still occurs in the latest version

![IMG_20211016_195720.jpg](https://user-images.githubusercontent.com/92644280/137597486-04ed393e-1693-4e71-8a5c-5e54dcb26e72.jpg)

**Comment by davidkgriggs** [comment]
Fixed in v1.0.7
