### ISSUE TITLE
Lagging UI

### ISSUE THREAD

**Issue by RangerXR1** [davidkgriggs/PlayniteModernUI#17]
the game detail menu is lagging in some time.. and also the main menu..
no smoothness in the game detail menu transition

**Comment by davidkgriggs** [comment]
Are you setting anything the DKG Theme Modifier? If so what settings?
Could you send a video of the lag please?

**Comment by DoganM95** [comment]
I've noticed the same issue. I have a 144Hz Monitor and the UI feels like 20 - 30 fps when navigating, giving that "laggy feeling". 

My DKG config:
![image](https://user-images.githubusercontent.com/38842553/140642215-205899d4-90c8-469d-976f-fd29e03b1570.png)

A video of the lag would not make much sense here i think, as you don't have a 60 or more fps comparison for that to visually see the issue.

**Comment by davidkgriggs** [comment]
Rounded corners uses a lot of cpu and ram to achieve, it's an issue with WPF applications. That's why it is turned off by default. Try disabling that and setting the image rendering in fullscreen settings to balanced if you don't have it set to that and see how it is then.

**Comment by DoganM95** [comment]
Disabling rounded corners worked, feels a lot smoother now, thanks!
