### ISSUE TITLE
Background changes and fluctuates in brightness in the absence of microtrailers / Requests

### ISSUE THREAD

**Issue by theoavila422** [davidkgriggs/PlayniteModernUI#19]
When I have a video background set on with DKG theme modifier, the backgrounds would change with increased brightness and then back if I don't have a micro trailer set. Any way around this? I only want to have a select few with micro trailers but for the rest, the change in brightness and back is very noticeable.

Having the trailer window only appearing in titles with a trailer video set would also be amazing.
Another request is an option to toggle play time/ last played and "how long to beat" off.

**Comment by davidkgriggs** [comment]
Fixed in v1.1.0
