### ISSUE TITLE
A boxed outline appears pressing  Rb or Lb

### ISSUE THREAD

**Issue by theoavila422** [davidkgriggs/PlayniteModernUI#20]
Only happens if coming from a long list, and then I change presets with Lb or Rb. Does not occur if I came from a list where everything fits in one screen. It disappears after navigating through the list but remains when navigating presets.

![Untitled](https://user-images.githubusercontent.com/93443697/139542629-c64f8a93-557f-4c3e-89dc-3e88c7303439.png)

**Comment by davidkgriggs** [comment]
Fixed in v1.1.0
