### ISSUE TITLE
Intro Video's audio plays randomly,  background flashing every so often

### ISSUE THREAD

**Issue by SuperJayRay** [davidkgriggs/PlayniteModernUI#21]
When I have an intro video with sound, the background will randomly flash and the sound from the video plays again. Happens about every few minutes, I don't remember it happening I before downloading micro trailers.

Also the the new Filter Icons horizontal menu makes it impossible to access the Grid and Setting switches.

**Comment by davidkgriggs** [comment]
Can you attach a video of the Video Intro issue please?

You should be able to navigate to the grid view and settings buttons. Go down to the games from the filter Presets and then across to those buttons.

**Comment by davidkgriggs** [comment]
Fixed in v1.2.0
