### ISSUE TITLE
Video Previews broke on Extra Metadata Tools update

### ISSUE THREAD

**Issue by DoganM95** [davidkgriggs/PlayniteModernUI#22]
Lately the ExtraMetadataToolsVideo extension deprecated and was replaced by ExtraMetadataLoader. 
Thus the current Microtrailers and Trailers don't work in ModernUI, until the new implementation (ExtraMetadataLoader) is used.

![image](https://user-images.githubusercontent.com/38842553/140642332-cea90e40-eb31-4486-bb9e-0aad6d3ad429.png)

Could you please update the skin, so trailers work again?

**Comment by davidkgriggs** [comment]
It does still work. You just have to have the fullscreen helper extension installed.
