### ISSUE TITLE
Cannot put focus on sidebar scrollbar

### ISSUE THREAD

**Issue by whoozwah** [davidkgriggs/PlayniteModernUI#24]
On the main screen (in grid view or list view) if the sidebar is enabled and the description is longer than the window a scrollbar shows up but is only accessible via the mouse. When using a controller there isn't actually a way to navigate over to the scrollbar and interact with it.

Desired behavior would be to allow use to input Circle/B to put focus on scroll bar and use up and down or right stick up and down to interact with it. left arrow input would put focus on filter presets.

**Comment by davidkgriggs** [comment]
Unfortunately I don't have that much control from themes. This would not be possible. Making the description area focusable causes issues elsewhere. Realistically you'd go to the Game Details page to read the full description, and the Main page just shows a snippet of the description, I wanted to have an ellipses (...) at the end of the description, but that is also not possible as the descriptions have to be in a HTML View which doesn't have that feature.
