### ISSUE TITLE
Game details page input focus issue

### ISSUE THREAD

**Issue by whoozwah** [davidkgriggs/PlayniteModernUI#25]
Upon first entering the game details window it doesn't appear there is any object in focus. You must arrow down or right twice before the play button gains focus. The first arrow down or right input it produces the black line which an issue was already raised here: https://github.com/davidkgriggs/PlayniteModernUI/issues/23

Also with the play button in focus, 1 down arrow input raises the interface up to expose the game description which seems to work like it should. However to return to the play button it requires 3 up arrow inputs to return the play button to focus. 

First input puts a highlighted box around the game description object
Second input returns the interface back to the default orientation but also brings back the aforementioned black line
Third input finally regains focus of the play button.

Desired behavior would most likely be to have the play button be in focus upon entering the game details screen, 1 down arrow would expose the description object and 1 up arrow input would restore orientation while simultaneously putting focus back on the play button object.

**Comment by davidkgriggs** [comment]
Fixed in v1.2.2
