### ISSUE TITLE
Toggle for Platform and year visibility 

### ISSUE THREAD

**Issue by C0D10X** [davidkgriggs/PlayniteModernUI#26]
Just like the description toggle. So you can hide the platform and the year under the logo.

![IMG_20211113_180206.jpg](https://user-images.githubusercontent.com/92644280/141652409-7e210549-6480-4cba-8bc5-7a2452dd149e.jpg)

**Comment by davidkgriggs** [comment]
Now linked to the Description On Off setting in v1.2.3, no ETA on release.
