### ISSUE TITLE
Configuration of description font size

### ISSUE THREAD

**Issue by C0D10X** [davidkgriggs/PlayniteModernUI#27]
For TV usage, the font size of the descriptions are too small and different from all the other font sizes:

![Unbenannt.png](https://user-images.githubusercontent.com/92644280/141652644-2e724dd6-4065-4cd7-b1a5-92c68a4c16cf.png)

A configurable font size would be awesome.

**Comment by davidkgriggs** [comment]
Font size is now linked for Font Size Small in v1.2.3, no ETA on release.
