### ISSUE TITLE
Details screen problem.

### ISSUE THREAD

**Issue by damianshrinivas** [davidkgriggs/PlayniteModernUI#31]
Ok so when I go to details screen I see this, cut in half. Is there a way to fix that?
![Desktop Screenshot 2021 11 14 - 02 11 26 01](https://user-images.githubusercontent.com/19475260/141663910-d3fa18b5-3f81-4b47-bdbc-3ee8f2807fd1.png)

**Comment by davidkgriggs** [comment]
It is a scrollable page now, this is not an issue.
