### ISSUE TITLE
Option to add borders and/or drop shadows to fonts

### ISSUE THREAD

**Issue by chidniu** [davidkgriggs/PlayniteModernUI#32]
On bright background images white font is hard or impossible to read. This could be mitigated by an option to activate font borders and/or drop shadows. I also think that drop shadows would look pretty cool, regardless of legibility issues 💯 

PS: Thanks for making and maintaining this theme. It's an absolute joy to use.

**Comment by davidkgriggs** [comment]
Drop shadows cause performance issues if used a lot. When you say white font what doe you mean specifically? Would you want all text to have drop shadows everywhere or just certain text?

**Comment by chidniu** [comment]
Mainly the text in the library overview. Especially the game title and the title of the current filter.

**Comment by davidkgriggs** [comment]
This option will be available in v1.2.3, no ETA on release
