### ISSUE TITLE
[Bug] [Compatability] SuccessStory "Earned achievements" progress bar needs custom % variable

### ISSUE THREAD

**Issue by Naval-777** [davidkgriggs/PlayniteModernUI#33]
The "Earned Achievements" progress bar found in the "Games Details" tab in the fullscreen theme shows the progress % out of 100 instead of the amount of achievements that the game contains. My two examples of this are shown on Civilization 5 (34 out of 286 unlocked, however progress bar appears to be 34% across) and The Binding of Isaac: Rebirth (171 out of 637 unlocked, progress bar is stretched more than other games to accommodate for a number above 100, this effect also happens on Mass Effect: LE with all 127 achievements unlocked).

![civilization5bug](https://user-images.githubusercontent.com/94616409/142971335-67439a53-34b6-48b7-981c-9b6c21aca014.PNG)
![isaacbug](https://user-images.githubusercontent.com/94616409/142971341-fab6f6ea-3750-456c-9fc1-04e498d5f912.PNG)
![masseffectbug](https://user-images.githubusercontent.com/94616409/142971348-e131728d-4a97-491e-83cd-49fcadb6c61c.PNG)

I initially made a issue thread on the SuccessStory page but the author believes that the issue is related to the code for this theme, specifically this line: https://github.com/davidkgriggs/PlayniteModernUI/blob/9bee29dc71245501710e38d5a28bedc4d1db3a2a/source/Views/GameDetails.xaml#L312 and I replaced
Width="100"
with
Width="{PluginSettings Plugin=SuccessStory, Path=Total}"
however this only increased the size of the progress bar to the maximum size at the same ratio instead of asking the progress bar to increase in individual intervals until reaching the maximum. Here's the result.

![uhohnotgood](https://user-images.githubusercontent.com/94616409/142971687-7f74ee38-dac8-45a9-8a7c-e6549cbd05d2.PNG)

This is all the information I have about the issue before being directed here.

**Comment by davidkgriggs** [comment]
Fixed in v1.2.3, no ETA on release right now though.
