### ISSUE TITLE
[Request] Better 4K/Ultrawide Support

### ISSUE THREAD

**Issue by drnooooo** [davidkgriggs/PlayniteModernUI#35]
Thank you so much for the theme! It's fantastic. However, although I know this is niche for most people, I would like to see better support for 4K and Ultrawide resolutions, as there's a lot of empty space in them.

![image](https://user-images.githubusercontent.com/33107312/143942910-1b354e4c-e390-4779-b3f8-fc809d8255d0.png)

For instance as you can see in here, there's a huge amount of empty space next to the RDR2 description. It would be great if there was an option to fill it with something - video trailers, achievement data, screeenshots, etc.

The same thing is the case with the details screen:

![image](https://user-images.githubusercontent.com/33107312/143943163-c55c67c9-1820-4d70-92b3-ec905da414b2.png)

Is there an option to move it upwards so that there isn't so much empty space at the top?

**Comment by SoulJaCKER12** [comment]
I have the same issue. We now have to scroll down to see the trailers. The issue did not exist in the first versions of the theme.

**Comment by davidkgriggs** [comment]
I will look into better ultra wide support. However scrolling down in the Game Details page is not a bug, it is a feature. It was mentioned in the changelog that the Game Details page had been reworked. As this theme is based on modern UI's a lot of them have a scrolling details page, that is why I added this. The theme is always going to change and evolve. If I see a Details page on a modern UI that I like more then I will replicate it for this theme.

**Comment by SoulJaCKER12** [comment]
I understand. Good to know that it is not a bug, but a deliberate decision. Maybe the game description and trailer can be slightly moved up or down so it doesn't look like a bug. Only seeing the top part of the game description and trailer make it seems like its a bug. It cuts the information at an awkward place. Loving the Theme otherwise. Thanks for your hard work!

**Comment by drnooooo** [comment]
Thank you very much for the response! Personally my preference would definitely be to have the trailer in the top of the details screen at least, but I understand if that's not what you want to do. I'm also grateful for you looking into ultra-wide support.

**Comment by SoulJaCKER12** [comment]
Last update fixed the odd placements of the features on an ultra wide screen . Here is how it looks now : 

[Screenshot (4)](https://user-images.githubusercontent.com/95514052/150574221-ab899139-4566-4a9e-b34d-4fa777e034e4.png)

Better than I could have imagined it. Beautiful!

Thank you for your hard work.

**Comment by drnooooo** [comment]
I agree, it looks a lot better now - thank you.
