### ISSUE TITLE
[Request] Make Handling of Custom Filter Icons More Convenient

### ISSUE THREAD

**Issue by burnpsy** [davidkgriggs/PlayniteModernUI#36]
Basically what the title says. The current method for custom filter icons is very unwieldly and requires either uploading icons to GitHub for everyone or having the end user navigate to the theme's directory to find the folder with the icons. Then every time the theme updates, there is an instruction to backup custom icons and the like. I'll be honest and say that the existence of this feature at all wasn't exactly obvious in the absence of the all caps warning on the patch notes.

As someone whose entire set of filters is weirdly named compared to other people, would it be possible to setup some sort of more convenient way of handling this? One thought that comes to mind would be the option to point DKG Theme Modifier to a folder with additional icons, and have the theme read those icons in addition to the ones bundled with the theme. This could also let the end user override the bundled icon without having to back that icon up.

That was just the first solution that came to mind, but the overall point is, please make this easier.

**Comment by davidkgriggs** [comment]
I have been working on this. It just isn't ready yet. There will be a new tab in the Playnite Modern UI section of the DKG Theme Modifier, it will have a button to open the directory to put your icons in. They will then remain even after updates as you said, hopefully I'll get around to finishing it sometime soon.

**Comment by davidkgriggs** [comment]
This is done in v1.3.0
