### ISSUE TITLE
[Request] Have an option for decription information to be shown further up on screen after selecting

### ISSUE THREAD

**Issue by IDFWT** [davidkgriggs/PlayniteModernUI#38]
Would it be possible to have the information for the games be shown further up after selecting them? I'm finding that every time I go to look at a game I'm pressing the down button to bring the information up to read the description.

What I'm currently seeing when selecting a game:
![Screenshot 1](https://user-images.githubusercontent.com/82745073/145580918-14e19f30-7808-4621-99c7-c36014f8c603.png)

What I would like to see when selecting the game:
![Screenshot 2](https://user-images.githubusercontent.com/82745073/145581108-d9827a1f-422a-4fb3-82f3-ee2c6e95a8a1.png)

I feel it would make using the theme a lot less cumbersome for me, but I understand a lot of people would enjoy having the artwork presented on its own. If there were an option to allow this I would seriously appreciate it! Love the theme regardless. Thank you!

**Comment by davidkgriggs** [comment]
I am currently re-working the game details page. It should sort your problem. No ETA on release though.

**Comment by IDFWT** [comment]
Awesome! Looking forwards to seeing what you come up with, I appreciate the work you've put into this!
