### ISSUE TITLE
Logos Not Showing Up in v1.4.0

### ISSUE THREAD

**Issue by RosellaCamella** [davidkgriggs/PlayniteModernUI#42]
If I update everything including both the update for Extra Metadata Extension and ModernUI, the logos in specifically the new [v1.4.0] ModernUI no longer work, but they do still work in other themes. If I update everything excluding the new [v1.4.0] ModernUI the logos still work in the ModernUI theme. Something appears to be incompatible between the two updates.

**Comment by davidkgriggs** [comment]
Have you ticked that you want logos in the DKG Theme Modifier and then clicked the Apply Changes button? That needs to be done each time the theme is updated as it goes back to default settings.

**Comment by davidkgriggs** [comment]
As there has been no replay on this I'm closing this issue.
