### ISSUE TITLE
Whole theme slows down after opening a description of any game

### ISSUE THREAD

**Issue by ShrimpDuck** [davidkgriggs/PlayniteModernUI#43]
Theme is plenty fast and snappy on first load but as soon as I open a description for a game and exit out, it is now stuttering and lagging when scrolling through games. Restarting fixes the issue until another description is opened.

Screen recording of issue: https://streamable.com/o8zzia

Specs:
Ryzen 3600
GTX 970
16gb DDR4
Installed on SSD

**Comment by davidkgriggs** [comment]
This is a known issue of Playnite itself, I think it was being fixed in v10. Might have to wait around to see if it's fixed in v10.

**Comment by davidkgriggs** [comment]
Fixed in v1.4.1
