### ISSUE TITLE
Custom Intro Video not replacing stock Intro Video

### ISSUE THREAD

**Issue by Deerhall** [davidkgriggs/PlayniteModernUI#5]
I've been trying to get my own Intro Video to work.

I hastily looked through the code to see if you accidentally wrote the wrong path in the instruction but it seemed to check out (Source="\ExtraMetadata\Themes\Fullscreen\PlayniteModernUI\IntroVideo.mp4).

I've attempted placing my "IntroVideo.mp4" in the following filepaths:
_C:\Users\deerhall\AppData\Playnite\ExtraMetadata\Themes\Fullscreen\PlayniteModernUI
C:\Users\deerhall\AppData\Roaming\Playnite\ExtraMetadata\Themes\Fullscreen\PlayniteModernUI
C:\Users\deerhall\AppData\Local\Playnite\ExtraMetadata\Themes\Fullscreen\PlayniteModernUI_

Currently running Playnite 9.1. (didn't work on portable beta2 earlier either)

**Comment by Deerhall** [comment]
Settings:
https://i.ibb.co/rm3VZz7/image.png
Default Intro:
https://i.ibb.co/64dfSf6/image.png

**Comment by davidkgriggs** [comment]
Fixed with the release of DKG Theme Modifier V2.1.0
