### ISSUE TITLE
[Bug] Theme crashes when opening filter panel

### ISSUE THREAD

**Issue by anesyd** [davidkgriggs/PlayniteModernUI#51]
https://user-images.githubusercontent.com/113592253/190370064-b65b0b28-32c3-4e36-9b13-dfc2295fedbc.mp4

**Comment by anesyd** [comment]
Also if possible, cause this is bothering me a little bit, can you add a space after commas when listing out game details (ex. Features: Single-player, Multiplayer). Minor quality of life thing. Other than that, your theme is perfect for me! Keep up the good work.

![Capture](https://user-images.githubusercontent.com/113592253/190373296-3f5ee81c-e05e-44c5-9347-ee4b50b8acd0.PNG)

**Comment by davidkgriggs** [comment]
It's a problem with P9 when you upgrade to P10 it will be work fine. P10 public release is aiming for 20th of September. The space after commas immortals not sure I can add. I'm using a built in function in Playnite to convert a list to string to render them out. I'll have a look though.

**Comment by anesyd** [comment]
I see. I'll look out for the update then. Thanks!
