### ISSUE TITLE
Use Logo in place of title doesn't change the main view

### ISSUE THREAD

**Issue by ch4nny** [davidkgriggs/PlayniteModernUI#52]
Toggling the Use Logo in Place of Title option in DKG Theme Modifier changes the detail view but not the main view
![image](https://user-images.githubusercontent.com/79906474/190865142-0ccc868e-c413-4e20-9501-fd178a5f208e.png)
![image](https://user-images.githubusercontent.com/79906474/190865149-a9b38f49-074c-4919-978c-d9643b758e56.png)

**Comment by cnapolit** [comment]
Not personally seeing this issue as of the latest release. Just to double check, make sure to hit apply in the settings.

**Comment by ch4nny** [comment]
Tried everything in settings. Every option works fine except for the matter at hand.

**Comment by ch4nny** [comment]
@davidkgriggs

**Comment by davidkgriggs** [comment]
Do you have Extra Metadata Loader and Extra Metadata Fullscreen Helped installed?

**Comment by ch4nny** [comment]
I forgot to install Extra Metadata Fullscreen Helper! Thank you and solved.
