### ISSUE TITLE
Trailers Large with no Sound

### ISSUE THREAD

**Issue by RosellaCamella** [davidkgriggs/PlayniteModernUI#54]
After updating The DKG Theme Modifier to v2.8.1 and ModernUi to 1.5.2, video trailers are now the span of the screen behind the background image and do not have any sound even when hitting the Play Video Audio button. The only way you can get sound currently is going in the Settings of Extra Metadata Loader and unchecking Play Videos Initially Without Sound. However in doing so, you cannot mute the videos. Hitting mute with this option unchecked will let the Playnite background music and video audio play at the same time. I have tried turning off and on different settings and hitting Apply and have also restarted my system. Would this be a ModernUI issue?

**Comment by davidkgriggs** [comment]
Hi there. Now that Modern UI uses the Extra Metadata Loader to play trailers for a smoother experience some of the functionality has been lost for now. You can read what does what in the Wiki guide here: https://github.com/davidkgriggs/PlayniteModernUI/wiki

**Comment by RosellaCamella** [comment]
I guess my only question then is how do you fix the sound bug I motioned where if you have "videos start without sound" checked, you trailer has no sound regardless of whether you unmute it or not, but when you uncheck that, the trailer always plays sound even over the home theme whether you press mute or not.

**Comment by davidkgriggs** [comment]
v1.6.0 will have new media controls that mute the sound of the video correctly.
