### ISSUE TITLE
preserve original cover art ratio

### ISSUE THREAD

**Issue by super-lurker** [davidkgriggs/PlayniteModernUI#6]
I understand that box art style covers are the new fav at the moment, but dvd cover art style has and still is being use in todays physical dvd releases. I would love to see an option for this in a future update. thanks

**Comment by davidkgriggs** [comment]
It is the height of the covers that is causing your issue, they're squashing. Increase the amount of items on the row in the layout settings in fullscreen. You should then see your full dvd covers.
