### ISSUE TITLE
Would love the Simpleish layout

### ISSUE THREAD

**Issue by jamie9090** [davidkgriggs/PlayniteModernUI#8]
I was in love with Simpleish, and after moving to Playnite 9, I'm gutted that I can't use it anymore

Are you planning on porting that theme to Playnite 9, or bringing its UI to this theme?

**Comment by jamie9090** [comment]
No problems at all, I appreciate what you do.

My favourite part of SIMEPLEish was the UI and UX. Colours, fonts, layouts etc.

I'll move over to PS5ish for now. They're all awesome!

**Comment by davidkgriggs** [comment]
I'll be releasing a Playnite 9 version of SIMPLEish at some point, will resolve these issues
